server:
  port: 9070
spring:
  application:
    name: customer-service
  r2dbc:
    username: postgres
    password: root
    url: r2dbc:postgresql://localhost:5432/postgres?serverTimezone=America/Lima
